"""Add opinion field in user_movie table

Revision ID: 36f6c2ca1021
Revises: 
Create Date: 2024-11-16 22:49:19.137320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f6c2ca1021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opinion', sa.Enum('LOVED_IT', 'DIDNT_LIKE_IT', 'WANT_TO_WATCH', 'PASS', name='opinion'), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('opinion')

    # ### end Alembic commands ###
